# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy SNAPSHOT ParCEFone with Maven

on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: verify with Maven
        run: mvn --settings settings.xml --batch-mode --update-snapshots verify

      - name: Publish to GitHub Packages Apache Maven
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: mvn --settings settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
