# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verify and deploy ParCEFone with Maven

on:
  pull_request:
    types: [closed]
    branches: [next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: verify with Maven
        run: mvn -Pcontrib-check --batch-mode --update-snapshots verify

      - name: Publish SNAPSHOT to Sonatype Maven Central
        if: github.event.pull_request.merged == true
        run: mvn -Pcontrib-check --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}